name: instrumentation_client
version: 6.0.0
description: A client reporting library for instrumentation
dependencies:
  bignum: ^0.0.7
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.11.1+1 <0.12.0'
dev_dependencies:
   unittest: '>=0.10.0'
